apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the service
      targetPort: 8080 # Port on the pod the service forwards to
      nodePort: 30001  # Optional: Port accessible externally on each node
